import { StyleSheet } from 'react-native';

export const palette = {
  background: '#F8F5EF', card: '#FFFFFF', text: '#202827', muted: '#6B7270',
  green: '#218653', greenSoft: '#E6F3EA', amber: '#E99A13', amberSoft: '#FFF2D9',
  coral: '#DE4248', coralSoft: '#FCE9E9', purple: '#70465F', purpleSoft: '#F4EAF1',
  border: '#E8E4DC',
};
export const ui = StyleSheet.create({
  page: { flex: 1, backgroundColor: palette.background },
  content: { paddingHorizontal: 16, paddingTop: 18, paddingBottom: 28, gap: 16 },
  title: { color: palette.text, fontSize: 27, fontWeight: '700' },
  subtitle: { color: palette.muted, fontSize: 15, lineHeight: 22 },
  card: { backgroundColor: palette.card, borderRadius: 20, borderWidth: 1,
    borderColor: palette.border, padding: 18, gap: 9 },
  cardTitle: { color: palette.text, fontSize: 18, fontWeight: '700' },
  body: { color: palette.text, fontSize: 15, lineHeight: 22 },
  muted: { color: palette.muted, fontSize: 14, lineHeight: 21 },
  warning: { color: palette.coral, fontSize: 14, lineHeight: 21 },
  label: { color: palette.text, fontSize: 15, fontWeight: '600' },
  input: { backgroundColor: '#fff', borderWidth: 1, borderColor: palette.border,
    borderRadius: 12, color: palette.text, fontSize: 16, padding: 13 },
  button: { backgroundColor: palette.green, padding: 15, borderRadius: 12, alignItems: 'center' },
  buttonText: { color: '#fff', fontWeight: '700', fontSize: 16 },
  secondaryButton: { padding: 13, borderWidth: 1, borderColor: palette.border,
    borderRadius: 12, alignItems: 'center' },
  secondaryText: { color: palette.text, fontWeight: '600', fontSize: 15 },
});

export const design = StyleSheet.create({
  pageContent: { paddingHorizontal: 16, paddingTop: 14, paddingBottom: 28, gap: 16 },
  homePageContent: { paddingHorizontal: 16, paddingTop: 10, paddingBottom: 24, gap: 10 },
  homeWideContent: { width: '100%', maxWidth: 720, alignSelf: 'center' },
  homeNarrowPageContent: { paddingHorizontal: 14, paddingTop: 8, gap: 8 },
  homeHero: { minHeight: 112, padding: 14, borderRadius: 22, backgroundColor: '#F1EBDD',
    flexDirection: 'row', alignItems: 'center', overflow: 'hidden' },
  homeHeroCompact: { padding: 12 },
  heroCopy: { flex: 1, gap: 5, zIndex: 1 },
  eyebrow: { color: palette.green, fontSize: 12, fontWeight: '700', letterSpacing: 0.6 },
  heroTitle: { color: palette.text, fontSize: 27, lineHeight: 32, fontWeight: '800' },
  heroSubtitle: { color: '#59615B', fontSize: 13, lineHeight: 19, maxWidth: 190 },
  heroArt: { width: 92, height: 84, marginRight: -4, borderRadius: 26,
    backgroundColor: '#E7DCC9', alignItems: 'center', justifyContent: 'center' },
  heroArtCompact: { width: 76, height: 76 },
  heroArtCircle: { position: 'absolute', width: 56, height: 56, borderRadius: 28,
    backgroundColor: '#F8F1E5', right: 6, top: 4 },
  summaryRow: { flexDirection: 'row', gap: 8 },
  summaryCard: { flex: 1, minHeight: 76, borderRadius: 16, padding: 10,
    flexDirection: 'row', alignItems: 'center', gap: 8 },
  summaryGreen: { backgroundColor: palette.greenSoft },
  summaryRed: { backgroundColor: palette.coralSoft },
  summaryIcon: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center' },
  summaryNumber: { fontSize: 25, lineHeight: 29, fontWeight: '800' },
  summaryLabel: { color: palette.text, fontSize: 12, lineHeight: 16, fontWeight: '600' },
  sectionHeading: { color: palette.text, fontSize: 19, fontWeight: '700' },
  sectionRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  sectionAction: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 8 },
  sectionLink: { color: palette.muted, fontSize: 13, fontWeight: '600' },
  deviceGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  deviceTile: { width: '48%', minHeight: 120, padding: 10, borderRadius: 16,
    backgroundColor: palette.card, borderWidth: 1, borderColor: palette.border, gap: 6 },
  deviceTileTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  deviceArt: { width: 44, height: 44, borderRadius: 14, backgroundColor: '#F3F2EE', alignItems: 'center', justifyContent: 'center' },
  deviceTileTitle: { color: palette.text, fontSize: 14, fontWeight: '700' },
  deviceTileMeta: { color: palette.muted, fontSize: 11, lineHeight: 15 },
  homeDeviceTileMeta: { color: palette.muted, fontSize: 12, lineHeight: 16 },
  statusPill: { borderRadius: 20, paddingHorizontal: 9, paddingVertical: 5,
    flexDirection: 'row', alignItems: 'center', gap: 5, alignSelf: 'flex-start' },
  statusText: { fontSize: 11, fontWeight: '700' },
  featureBanner: { minHeight: 82, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 16,
    backgroundColor: '#EFE5D5', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', overflow: 'hidden' },
  featureTitle: { color: palette.text, fontSize: 16, lineHeight: 22, fontWeight: '700' },
  featureSubtitle: { color: palette.muted, fontSize: 12 },
  filterList: { gap: 8, paddingRight: 16 },
  filterChip: { paddingHorizontal: 15, paddingVertical: 9, borderRadius: 24,
    backgroundColor: '#F1F0EC', flexDirection: 'row', alignItems: 'center', gap: 5 },
  filterChipActive: { backgroundColor: palette.greenSoft },
  filterText: { color: palette.text, fontSize: 13, fontWeight: '600' },
  filterTextActive: { color: palette.green, fontWeight: '700' },
  noticeCard: { padding: 15, borderRadius: 19, backgroundColor: palette.card,
    borderWidth: 1, borderColor: palette.border, gap: 10 },
  homeNoticeCard: { padding: 13, borderRadius: 17, backgroundColor: palette.card,
    borderWidth: 1, borderColor: palette.border, gap: 8 },
  noticeCritical: { backgroundColor: '#FFF0EE', borderColor: '#F7DEDB' },
  noticeHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 11 },
  noticeIcon: { width: 42, height: 42, borderRadius: 15, alignItems: 'center', justifyContent: 'center' },
  noticeCopy: { flex: 1, gap: 4 },
  noticeDate: { color: palette.muted, fontSize: 11 },
  noticeTitle: { color: palette.text, fontSize: 15, lineHeight: 20, fontWeight: '700' },
  noticeSummary: { color: '#454D4A', fontSize: 13, lineHeight: 19 },
  noticeMeta: { color: palette.muted, fontSize: 11, lineHeight: 16 },
  homeNoticeMeta: { color: palette.muted, fontSize: 12, lineHeight: 17 },
  noticeActions: { flexDirection: 'row', gap: 8, marginTop: 1 },
  noticeAction: { flex: 1, paddingVertical: 10, paddingHorizontal: 8, borderRadius: 12,
    borderWidth: 1, borderColor: '#D8CEC8', alignItems: 'center', justifyContent: 'center' },
  noticeActionPrimary: { backgroundColor: palette.coral, borderColor: palette.coral },
  noticeActionText: { color: palette.text, fontSize: 12, fontWeight: '700' },
  noticeActionTextLight: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  emptyState: { padding: 22, alignItems: 'center', gap: 9 },
  detailHero: { minHeight: 150, padding: 18, borderRadius: 23, backgroundColor: '#F1EBDD',
    flexDirection: 'row', alignItems: 'center', overflow: 'hidden' },
  detailArt: { width: 112, height: 112, borderRadius: 26, backgroundColor: '#E5DCCF',
    alignItems: 'center', justifyContent: 'center' },
  detailSection: { backgroundColor: palette.card, borderRadius: 19, padding: 16,
    borderWidth: 1, borderColor: palette.border, gap: 12 },
  detailSectionTitle: { color: palette.text, fontSize: 16, fontWeight: '700' },
  trafficLegend: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  legendItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  legendText: { color: palette.muted, fontSize: 11 },
  detailRow: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: 11,
    paddingVertical: 9, borderBottomWidth: 1, borderColor: '#F0EDE8' },
  detailRowIcon: { width: 38, height: 38, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  detailRowText: { flex: 1, gap: 2 },
  detailRowTitle: { color: palette.text, fontSize: 13, fontWeight: '700' },
  detailRowSubtitle: { color: palette.muted, fontSize: 11 },
  ctaPurple: { backgroundColor: palette.purple, borderRadius: 13, padding: 14, alignItems: 'center' },
  ctaPurpleText: { color: '#FFFFFF', fontSize: 14, fontWeight: '700' },
});
